/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppSourcesRouteImport } from './routes/_auth/app/sources'
import { Route as AuthAppRoutinesRouteImport } from './routes/_auth/app/routines'
import { Route as AuthAppOnboardingRouteImport } from './routes/_auth/app/onboarding'
import { Route as AuthAppDigestRouteImport } from './routes/_auth/app/digest'
import { Route as AuthAppDemoRouteImport } from './routes/_auth/app/demo'
import { Route as AuthAppChatRouteImport } from './routes/_auth/app/chat'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppSourcesRoute = AuthAppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppRoutinesRoute = AuthAppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppOnboardingRoute = AuthAppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppDigestRoute = AuthAppDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppDemoRoute = AuthAppDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppChatRoute = AuthAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/chat': typeof AuthAppChatRoute
  '/app/demo': typeof AuthAppDemoRoute
  '/app/digest': typeof AuthAppDigestRoute
  '/app/onboarding': typeof AuthAppOnboardingRoute
  '/app/routines': typeof AuthAppRoutinesRoute
  '/app/sources': typeof AuthAppSourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/chat': typeof AuthAppChatRoute
  '/app/demo': typeof AuthAppDemoRoute
  '/app/digest': typeof AuthAppDigestRoute
  '/app/onboarding': typeof AuthAppOnboardingRoute
  '/app/routines': typeof AuthAppRoutinesRoute
  '/app/sources': typeof AuthAppSourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/chat': typeof ApiChatRoute
  '/_auth/app/chat': typeof AuthAppChatRoute
  '/_auth/app/demo': typeof AuthAppDemoRoute
  '/_auth/app/digest': typeof AuthAppDigestRoute
  '/_auth/app/onboarding': typeof AuthAppOnboardingRoute
  '/_auth/app/routines': typeof AuthAppRoutinesRoute
  '/_auth/app/sources': typeof AuthAppSourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/chat'
    | '/app/demo'
    | '/app/digest'
    | '/app/onboarding'
    | '/app/routines'
    | '/app/sources'
    | '/api/auth/$'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/chat'
    | '/app/demo'
    | '/app/digest'
    | '/app/onboarding'
    | '/app/routines'
    | '/app/sources'
    | '/api/auth/$'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/api/chat'
    | '/_auth/app/chat'
    | '/_auth/app/demo'
    | '/_auth/app/digest'
    | '/_auth/app/onboarding'
    | '/_auth/app/routines'
    | '/_auth/app/sources'
    | '/api/auth/$'
    | '/_auth/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/sources': {
      id: '/_auth/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AuthAppSourcesRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/routines': {
      id: '/_auth/app/routines'
      path: '/routines'
      fullPath: '/app/routines'
      preLoaderRoute: typeof AuthAppRoutinesRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/onboarding': {
      id: '/_auth/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthAppOnboardingRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/digest': {
      id: '/_auth/app/digest'
      path: '/digest'
      fullPath: '/app/digest'
      preLoaderRoute: typeof AuthAppDigestRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/demo': {
      id: '/_auth/app/demo'
      path: '/demo'
      fullPath: '/app/demo'
      preLoaderRoute: typeof AuthAppDemoRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/chat': {
      id: '/_auth/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthAppChatRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppChatRoute: typeof AuthAppChatRoute
  AuthAppDemoRoute: typeof AuthAppDemoRoute
  AuthAppDigestRoute: typeof AuthAppDigestRoute
  AuthAppOnboardingRoute: typeof AuthAppOnboardingRoute
  AuthAppRoutinesRoute: typeof AuthAppRoutinesRoute
  AuthAppSourcesRoute: typeof AuthAppSourcesRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppChatRoute: AuthAppChatRoute,
  AuthAppDemoRoute: AuthAppDemoRoute,
  AuthAppDigestRoute: AuthAppDigestRoute,
  AuthAppOnboardingRoute: AuthAppOnboardingRoute,
  AuthAppRoutinesRoute: AuthAppRoutinesRoute,
  AuthAppSourcesRoute: AuthAppSourcesRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
